### PR TITLE
Added monospace converted version of OpenDyslexic Regular

### PR DESCRIPTION
**Pull request by GhostDog98**
Many issues have been opened with this request, so I've quickly converted OpenDyslexic Regular to monospace.

### CODE REVIEW

**Comment by sthibaul** [comment]
Well, thanks but it looks bogus. For instance, the 'a' character is apparently using the alta version rather than the regular version. Also, the 'é' character has its accent below instead of above. I don't really understand why these issues: they were not appearing with the mono variant provided in the 20160623 release from https://github.com/antijingoist/open-dyslexic/tags

**Comment by sthibaul** [comment]
Also, the @ character is very small, basically unreadable.

**Comment by GhostDog98** [comment]
Hi,

I cannot reproduce either issue with the 'a' character, nor the one with the 'e' character, could you please provide a screenshot? As for the '@' symbol, I'll work on fixing that, thanks for the feedback!

**Comment by sthibaul** [comment]
Here it is:
blip

**Comment by GhostDog98** [comment]
Hi, I've just fixed the @ symbol, I was completely unaware of the fact there were official releases of the font in mono-space, thus making this irrelevant, thanks for your patience with me lol.

**Pull request closed without merging**
